### ISSUE TITLE
The control range of mount joints in the CatchUnder/Overarm env.

### ISSUE THREAD

**Issue by Jianshu-Hu** [henrycharlesworth/dexterous-gym#1]
Hi Henry, hope you are doing well! 
I have a question about the control range of the mount joints of the hands. In the file `envs/hand/egg_catch_underarm.xml`, the control range is defined in [this part](https://github.com/henrycharlesworth/dexterous-gym/blob/2d4902d26b61c78871206c2c912566d68d7634ea/dexterous_gym/envs/hand/egg_catch_underarm.xml#L386-L400) which is (-1, 1) for the translation. I noticed that the joint for x-axis translation can only move within (-0.2, 0.2) when the control was set within (-1, 1). And similarly for other joints , the acutual control range were all smaller than (-1, 1). 
However, I didn't find where this came from. I will appreciate it if you could give me some explanation. Thanks!

Best regard!

**Comment by henrycharlesworth** [comment]
Hi, apologies for the late response! The honest answer is I can't really remember why this was set up like this. I'm not really an expert in Mujoco and this was my first attempt at modifying a set of Mujoco environments, so I just experimented with various parameters until I got the hand to be constrained to be within a region that I was happy with.

**Comment by Jianshu-Hu** [comment]
Thank you so much for your reply. I have figured out how to set the range in the mujoco files. By modifying `gainprm` and `biasprm` in this line, the range can be changed.
https://github.com/henrycharlesworth/dexterous-gym/blob/dd047ad7f47ba78e2a4e2642e39bc0c0b778e594/dexterous_gym/envs/hand/egg_catch_underarm.xml#L387
