### ISSUE TITLE
The code is stuck in gym.make() ?

### ISSUE THREAD

**Issue by Ray006** [henrycharlesworth/dexterous-gym#2]
The code is stuck in this line:
env = gym.make("EggCatchUnderarm-v0")

my package versions:
gym=0.21.0
mujoco-py=1.50.1.68

I have tried both ways below but got the same thing. The code is stuck in gym.make() without any warning or error.

dexterous-gym=0.1.6 (clone the code and pip install -e .)
dexterous-gym=0.1.7 (pip install dexterous-gym)

**Comment by henrycharlesworth** [comment]
Hmmm, that's odd. I hope it's just a package version issue or something. I have it working with an environment with:

gym=0.15.3
dexterous-gym=0.1.7
mujoco-py=2.0.2.13

My guess is that it either requires that specific gym version or that specific mujoco_py version. Can you see if it works with those?

**Comment by Ray006** [comment]
It helps. Thanks.
